// response of display is status and arr of books (cartitems)
import { Book } from './book';

export interface CartItem { // data in each book
    book: Book;
    quantity: number;
    _id: string; // cart item id generated by backend
}
